#!/sbin/sh
# Shell Script EDIFY Replacement

#Variables
OUTFD=/proc/self/fd/$2;
ZIPFILE="$3";
COMMONDIR=/tmp/AFZCScripts;
TMPDIR=/dev/tmp
NikGappsAddonDir="/system/addon.d/nikgapps"

addToLog() {
  echo "$1" >> "/tmp/NikGapps.log"
}

decrypt() {
  mkdir -p "$(dirname "$2")"
  addToLog "- decrypting $COMMONDIR/busybox"
  addToLog "  -> source $1"
  addToLog "  -> destination $2"
  unzip -o "$COMMONDIR/busybox" "$1" -p >"$2"
  chmod 755 "$2";
}

ui_print() {
  until [ ! "$1" ]; do
    echo "ui_print $1
      ui_print" >> "$OUTFD";
      addToLog "$1"
    shift;
  done;
}

# package_extract_file <file> <destination_file>
package_extract_file() { mkdir -p "$(dirname "$2")"; unzip -o "$ZIPFILE" "$1" -p > "$2"; }

# package_extract_dir <dir> <destination_dir>
package_extract_dir() {
  local entry outfile;
  for entry in $(unzip -l "$ZIPFILE" "$1/*" 2>/dev/null | tail -n+4 | grep -v '/$' | grep -o " $1.*$" | cut -c2-); do
    outfile="$(echo "$entry" | sed "s|${1}|${2}|")";
    mkdir -p "$(dirname "$outfile")";
    unzip -o "$ZIPFILE" "$entry" -p > "$outfile";
  done;
}

#-----------------------------------Execution Starts---------------------------------#

package_extract_file "tools/busybox" "$COMMONDIR/busybox"

decrypt "nikgapps_installer" "$COMMONDIR/nikgapps_installer"
decrypt "ak3mount" "$COMMONDIR/ak3mount.sh"
decrypt "addon" "$COMMONDIR/addon"
decrypt "header" "$COMMONDIR/header"
decrypt "functions" "$COMMONDIR/functions"
decrypt "nikgapps.sh" "$COMMONDIR/nikgapps.sh"
decrypt "file_size" "$COMMONDIR/file_size"

rm -f "$COMMONDIR/busybox"

# Mount the partitions
. $COMMONDIR/ak3mount.sh
# Install the stuff
. $COMMONDIR/nikgapps_installer "$2" "$3"
show_progress 1.00 0

# Store the size of partitions before installation starts
df > "$COMMONDIR/size_before.txt"
df -h > "$COMMONDIR/size_before_readable.txt"
# Setting up tools
SetupTools

